apiVersion: v1 #not apps/v1 for some reason
kind: Service
metadata:
  labels:
    app: backend
  name: backend
#Configuration for open ports for database
#spec:
# ports:
# - port: 6374
#   protocol: TCP
#   targetPort: 6374
# selector:
#   app: backend
# type: ClusterIP