name: JavaCI
on: push
#remove comments to create env-variable
#env
jobs:
  Clone-down:
    runs-on: ubuntu-latest
    steps:
      - name: Cloning
        uses: actions/checkout@v2
  Testing:
    runs-on: ubuntu-latest
    steps:
      - name: Testing
        run: chmod +x frontend/gotest.sh && frontend/gotest.sh