name: JavaCI
on: push
#remove comments to create env-variable
#env
jobs:
  Clone-down:
    runs-on: ubuntu-latest
    steps:
      - name: Cloning
        uses: actions/checkout@v2
      - name: Upload repository
        uses: actions/upload-artifact@v2
        with:
          name: basic code
          path: .
  Testing:
    runs-on: ubuntu-latest
    steps:
      - name: Download repository
        uses: actions/download-artifact@v2
        with:
          name: basic code
          path: .
      - name: Testing
        run: chmod +x frontend/gotest.sh && frontend/gotest.sh
