name: GitHub Actions Demo
on: [push]
jobs:
   runs-on: ubuntu-latest


name: Deployment

on:
  push:
  branches:
      - main

jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: 
      name: production
      url: https://github.com
    steps:
      - name: deployment
        # ...deployment-specific steps

name: staging 

on:
  push:
    branches:
      - main

jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: 
      name: production 
      url: https://github.com
    steps:
      - name: staging 
        # ...deployment-specific steps

name: production

on:
  push:
    branches:
      - main

jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: 
      name: production
      url: https://github.com
    steps:
      - name: production
        # ...deployment-specific steps        
